### ISSUE TITLE
安装启动问题，求指教

### ISSUE THREAD

**Issue by widthhieght** [brewlin/swoft-im#1]
您好，我按照您的步骤进行了安装 出现了一些问题：

1. 对每个服务执行了composer install
2. 然后对每个服务的配置文件进行了修改
/home/www/serviceim/gateway-api/config/properties/db.php
/home/www/serviceim/gateway-api/config/properties/cache.php
![253cc1145933ef7acf4dc58a4bf52b8](https://user-images.githubusercontent.com/19816573/55222864-e8004c00-5247-11e9-8de4-776bc3f13032.png)
![QQ截图20190329172828](https://user-images.githubusercontent.com/19816573/55224109-bb99ff00-524a-11e9-8a86-ad4624258918.png)

3. 然后启动docker，我的docker 看了一下版本是1.8
**执行 docker-compose up 报错，不知道什么问题，查了百度 以为是版本问题，后来把docker-compose.yml中的版本号改成了1或者1.8 都不行！**
![docer](https://user-images.githubusercontent.com/19816573/55223208-a91ec600-5248-11e9-82d9-f5cac422309e.png)

4. **然后启动单个服务的守护进程时 虽然都启动了 但是都有报错：**
gateway-api 启动后：
![1](https://user-images.githubusercontent.com/19816573/55223553-67424f80-5249-11e9-8b0f-b7cb0ba10bd5.png)

然后其他服务的守护进程启动后的报错也都一样
![2](https://user-images.githubusercontent.com/19816573/55223638-9d7fcf00-5249-11e9-9396-5fd9bb0c3dfd.png)

另外还有个问题：
**我这边 前端代码已经跑起来了，当登录的时候会访问下面这个接口进行登录，请问能否把服务端的nginx域名配置给出一份，让这边也能通过登录接口执行后端代码交互**
![QQ截图20190329174115](https://user-images.githubusercontent.com/19816573/55223952-56460e00-524a-11e9-8684-7c9539cfc3a2.png)

**Comment by brewlin** [comment]
- 你的swoole 版本是4以上么  我的是2.13  非全协程版本，可能你的高版本不兼容
- connection refuse 可能是你依赖的服务没有启动，这边rpc就会连接失败
- 我的docker版本是这个
![image](https://user-images.githubusercontent.com/17773920/56894807-9a326a00-6ab9-11e9-89a1-67e376f68e96.png)

**Comment by brewlin** [comment]
nginx配置 就是location 到 tp的public 目录就可以了

**Comment by jiqinwj** [comment]
@brewlin 大神方便加个QQ吗 我想把这个项目跑起来 需要您的指导

**Comment by brewlin** [comment]
就是这个邮箱




------------------ 原始邮件 ------------------
发件人: "Kris"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 上午10:20
收件人: "brewlin/swoft-im"<swoft-im@noreply.github.com>; 
抄送: "Holand"<97404667@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [brewlin/swoft-im] 安装启动问题，求指教 (#1)




@brewlin 大神方便加个QQ吗 我想把这个项目跑起来 需要您的指导
