### ISSUE TITLE
对于请求接口不能返回结果的问题如下，日志记录如下

### ISSUE THREAD

**Issue by fubing005** [brewlin/swoft-im#11]
![微信截图_20210310163802](https://user-images.githubusercontent.com/9304810/110602299-d314ed00-81c0-11eb-8678-327569f40219.png)

2021-03-10 16:46:43 [error] [swoft] [logid:60488773c13ee] [spanid:0] trace[ErrorHandler.php:36,Swoft\Core\ErrorHandler->handle]
 {
    "code": 4,
    "msg": "两次密码输入不一致",
    "data": [],
    "statusCode": 2001,
    "file": "/website/gateway-api/app/Controllers/Api/LoginController.php",
    "line": 86
}

**Comment by brewlin** [comment]
有啥问题么，你的密码不一致

**Comment by fubing005** [comment]
> 有啥问题么，你的密码不一致

我想问的是，返回的json数据在postman上不能打印的问题

**Comment by brewlin** [comment]
swoft-im/gateway-api/app/Exception/SwoftExceptionHandler.php /

```
    public function handlerException(Response $response, \Throwable $throwable)
    {
        $file      = $throwable->getFile();
        $line      = $throwable->getLine();
        $code      = $throwable->getCode();
        $exception = $throwable->getMessage();
        $data = [];
        $statusCode = 10000;
        if(property_exists($throwable,'data'))
            $data = $throwable->data;
        if(property_exists($throwable,'statusCode'))
            $statusCode = $throwable->statusCode;

        $data = ['code' => $code,'msg' => $exception,'data' => $data,'statusCode' => $statusCode, 'file' => $file, 'line' => $line];
        //你的那个日志就是在这里打印出来的，说明代码走到这里了，需要看看下面为什么没有响应给客户端      
        App::error(json_encode($data));
        $response->json($data);
        return $this->handleOrigin($response);
    }
```

密码不一致采用的是 throw抛出异常，然后有个全局捕获异常的类来统一处理

你手动调试下 `response->json($data)`这个就是返回客户端的代码，看看是哪里的问题，还有你php和swoole版本多少

**Comment by fubing005** [comment]
> swoft-im/gateway-api/app/Exception/SwoftExceptionHandler.php /
> 
> ```
>     public function handlerException(Response $response, \Throwable $throwable)
>     {
>         $file      = $throwable->getFile();
>         $line      = $throwable->getLine();
>         $code      = $throwable->getCode();
>         $exception = $throwable->getMessage();
>         $data = [];
>         $statusCode = 10000;
>         if(property_exists($throwable,'data'))
>             $data = $throwable->data;
>         if(property_exists($throwable,'statusCode'))
>             $statusCode = $throwable->statusCode;
> 
>         $data = ['code' => $code,'msg' => $exception,'data' => $data,'statusCode' => $statusCode, 'file' => $file, 'line' => $line];
>         //你的那个日志就是在这里打印出来的，说明代码走到这里了，需要看看下面为什么没有响应给客户端      
>         App::error(json_encode($data));
>         $response->json($data);
>         return $this->handleOrigin($response);
>     }
> ```
> 
> 密码不一致采用的是 throw抛出异常，然后有个全局捕获异常的类来统一处理
> 
> 你手动调试下 `response->json($data)`这个就是返回客户端的代码，看看是哪里的问题，还有你php和swoole版本多少

php7.1 swoole4.0.3

**Comment by brewlin** [comment]
目前swoft1 貌似没有支持swoole4。可以手动换成swoole2.1.3+试试
或者根据上面那个流程去排查看看能不能修复swoft本身的问题

**Comment by fubing005** [comment]
> 目前swoft1 貌似没有支持swoole4。可以手动换成swoole2.1.3+试试
> 或者根据上面那个流程去排查看看能不能修复swoft本身的问题

我试试，真的感谢你耐心讲解，菜鸟一枚，这是个好项目想学习学习

**Comment by fubing005** [comment]
> 目前swoft1 貌似没有支持swoole4。可以手动换成swoole2.1.3+试试
> 或者根据上面那个流程去排查看看能不能修复swoft本身的问题

想认识你，方便加个微信么，交个朋友

**Comment by brewlin** [comment]
lxd_97404667 这个

**Comment by fubing005** [comment]
> lxd_97404667 这个

加你了，抽空通过一下
