### ISSUE TITLE
docker-compose up 启动问题

### ISSUE THREAD

**Issue by jiqinwj** [brewlin/swoft-im#2]
![image](https://user-images.githubusercontent.com/16432577/57639402-6d667280-75e2-11e9-966e-59008daf9dc6.png)
这是啥问题 请指教

**Comment by brewlin** [comment]
mysql 没有连接上 ，可能有点问题 我改了后再提交下

**Comment by JimChenWYU** [comment]
@brewlin 启动了之后redis异常自动关闭了，日志输出:

`Could not open input file: /website/redis-service/bin/swoft`

---

看了一下redis-server 的 Dockerfile
```
ADD . /website/gateway-api

EXPOSE 8090

ENTRYPOINT ["php", "/website/redis-service/bin/swoft","rpc:start"]
```
应该是把 ADD . /website/gateway-api 改为 ADD . /website/redis-server

但是没生效...有可能是缓存问题，但是google不到解决方法

**Comment by lemonlyue** [comment]
@brewlin 请问一下`mysql connection refused`问题解决了吗，运行的时候遇到这个问题
