### ISSUE TITLE
我swoft启动不了，大神帮看一下呗

### ISSUE THREAD

**Issue by guojiqun** [brewlin/swoft-im#4]
![image](https://user-images.githubusercontent.com/45585506/63994062-ccb2a900-cb25-11e9-8fc0-4bf1000973c4.png)
composer install之后启动报这个错误  是因为我版本不兼容吗

**Comment by 13037158859** [comment]
请问你这边解决了吗？我也遇到同样的问题

**Comment by brewlin** [comment]
现在可以了，之前composer.json 依赖配置更改了不兼容

**Comment by guojiqun** [comment]
好的  谢谢



------------------ 原始邮件 ------------------
发件人: "brewlin"<notifications@github.com>; 
发送时间: 2019年10月12日(星期六) 晚上10:33
收件人: "brewlin/swoft-im"<swoft-im@noreply.github.com>; 
抄送: "Super群儿"<1754973335@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [brewlin/swoft-im] 我swoft启动不了，大神帮看一下呗 (#4)




现在可以了，之前composer.json 依赖配置更改了不兼容
