### ISSUE TITLE
关于版本问题

### ISSUE THREAD

**Issue by g1e2x87** [brewlin/swoft-im#5]
swoole 是否支持4+？
swoft 版本看见是1.0，如果要升级，影响会有那些？

如果可以的话，可以深入沟通下，我打算升级下，涉及到的框架或是swoole使用了哪些函数，还不是很清楚。

**Comment by brewlin** [comment]
swoft1不支持无缝升级到swoft2，暂时不支持sw4，升级到话需要业务代码迁移
