### ISSUE TITLE
大神，请问前端代码在哪里？

### ISSUE THREAD

**Issue by gaodeyang** [brewlin/swoft-im#7]

**Comment by brewlin** [comment]
Chat-view  就是了------------------ 原始邮件 ------------------
发件人: "gaodeyang"<notifications@github.com>
发送时间: 2020年3月23日(星期一) 晚上11:29
收件人: "brewlin/swoft-im"<swoft-im@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [brewlin/swoft-im] 大神，请问前端代码在哪里？ (#7)




 
&mdash;
