### ISSUE TITLE
项目能够正常启动，单独请求接口没有返回数据，只能在控制台打印，求指教

### ISSUE THREAD

**Issue by fubing005** [brewlin/swoft-im#9]
![微信截图_20210308170257](https://user-images.githubusercontent.com/9304810/110300415-cc0ba480-8031-11eb-9406-847f33c9f8fb.png)
![微信截图_20210308171540](https://user-images.githubusercontent.com/9304810/110300522-e9d90980-8031-11eb-8d89-e6dfd4c0c292.png)

**Comment by brewlin** [comment]
你是docker-compose 启动的么？

如果单独手动启动的话 打开日志应该会有提示

**Comment by fubing005** [comment]
用docker-compose 启动的，我单独启动试试看

**Comment by fubing005** [comment]
> 你是docker-compose 启动的么？
> 
> 如果单独手动启动的话 打开日志应该会有提示

对的，我用docker-compose启动的，那我试试你的方法
